import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "DeepFake",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
      <html lang="en">
        <body className="min-h-screen  flex flex-col ">
          {children}
          <Toaster position="bottom-right" richColors closeButton />
        </body>
      </html>
     
  );
}
